const ANIMAL_DETAIL_REQUEST = "ANIMAL_DETAIL_REQUEST";
const ANIMAL_DETAIL_SUCESS = "ANIMAL_DETAIL_SUCESS";
const ANIMAL_DETAIL_FAIL = "ANIMAL_DETAIL_FAIL";


const ANIMAL_LIST_REQUEST = "ANIMAL_LIST_REQUEST";
const ANIMAL_LIST_SUCESS = "ANIMAL_LIST_SUCESS";
const ANIMAL_LIST_FAIL = "ANIMAL_LIST_FAIL";

export { 
    ANIMAL_DETAIL_FAIL,
    ANIMAL_DETAIL_REQUEST,
    ANIMAL_DETAIL_SUCESS,
    ANIMAL_LIST_FAIL,
    ANIMAL_LIST_REQUEST,
    ANIMAL_LIST_SUCESS
};
