// Aqui irá ficar todas as constantes
// Elas serão usadas para quando criar actions eu não correr risco de digitar informações erradas
const ANIMAL_LIST_REQUEST = "ANIMAL_LIST_REQUEST";
const ANIMAL_LIST_SUCESS = "ANIMAL_LIST_SUCESS";
const ANIMAL_LIST_FAIL = "ANIMAL_LIST_FAIL";

const ANIMAL_DETAILS_REQUEST = "ANIMAL_DETAILS_REQUEST";
const ANIMAL_DETAILS_SUCESS = "ANIMAL_DETAILS_SUCESS";
const ANIMAL_DETAILS_FAIL = "ANIMAL_DETAILS_FAIL";

const ANIMAL_REGISTER_REQUEST = "ANIMAL_REGISTER_REQUEST";
const ANIMAL_REGISTER_SUCESS = "ANIMAL_REGISTER_SUCESS";
const ANIMAL_REGISTER_FAIL = "ANIMAL_REGISTER_FAIL";

const ANIMAL_DELETE_REQUEST = "ANIMAL_DELETE_REQUEST";
const ANIMAL_DELETE_SUCESS = "ANIMAL_DELETE_SUCESS";
const ANIMAL_DELETE_FAIL = "ANIMAL_DELETE_FAIL";




export {
  ANIMAL_LIST_FAIL,
  ANIMAL_LIST_SUCESS,
  ANIMAL_LIST_REQUEST,
  ANIMAL_DETAILS_REQUEST,
  ANIMAL_DETAILS_SUCESS,
  ANIMAL_DETAILS_FAIL,
  ANIMAL_REGISTER_FAIL,
  ANIMAL_REGISTER_REQUEST,
  ANIMAL_REGISTER_SUCESS,
  ANIMAL_DELETE_FAIL,
  ANIMAL_DELETE_SUCESS,
  ANIMAL_DELETE_REQUEST,
};
