const DONATION_SAVE_REQUEST = "DONATION_SAVE_REQUEST";
const DONATION_SAVE_SUCESS = "DONATION_SAVE_SUCESS ";
const DONATION_SAVE_FAIL = "ODER_SAVE_FAIL";

const DONATION_DETAIL_REQUEST = "DONATION_DETAIL_REQUEST";
const DONATION_DETAIL_SUCESS = "DONATION_DETAIL_SUCESS";
const DONATION_DETAIL_FAIL = "DONATION_DETAIL_FAIL";

const DONATION_DELETE_REQUEST = "DONATION_DELETE_REQUEST";
const DONATION_DELETE_SUCESS = "DONATION_DELETE_SUCESS";
const DONATION_DELETE_FAIL = "DONATION_DELETE_FAIL";

const DONATION_LIST_REQUEST = "DONATION_LIST_REQUEST";
const DONATION_LIST_SUCESS = "DONATION_LIST_SUCESS";
const DONATION_LIST_FAIL = "DONATION_LIST_FAIL";

export { 
    DONATION_SAVE_FAIL, 
    DONATION_SAVE_REQUEST, 
    DONATION_SAVE_SUCESS,
    DONATION_DELETE_SUCESS,
    DONATION_DELETE_FAIL,
    DONATION_DELETE_REQUEST,
    DONATION_DETAIL_FAIL,
    DONATION_DETAIL_REQUEST,
    DONATION_DETAIL_SUCESS,
    DONATION_LIST_FAIL,
    DONATION_LIST_REQUEST,
    DONATION_LIST_SUCESS
};
