const FAQ_SAVE_REQUEST = "FAQ_SAVE_REQUEST";
const FAQ_SAVE_SUCESS = "FAQ_SAVE_SUCESS ";
const FAQ_SAVE_FAIL = "ODER_SAVE_FAIL";

const FAQ_DETAIL_REQUEST = "FAQ_DETAIL_REQUEST";
const FAQ_DETAIL_SUCESS = "FAQ_DETAIL_SUCESS";
const FAQ_DETAIL_FAIL = "FAQ_DETAIL_FAIL";

const FAQ_DELETE_REQUEST = "FAQ_DELETE_REQUEST";
const FAQ_DELETE_SUCESS = "FAQ_DELETE_SUCESS";
const FAQ_DELETE_FAIL = "FAQ_DELETE_FAIL";

const FAQ_LIST_REQUEST = "FAQ_LIST_REQUEST";
const FAQ_LIST_SUCESS = "FAQ_LIST_SUCESS";
const FAQ_LIST_FAIL = "FAQ_LIST_FAIL";

export { 
    FAQ_SAVE_FAIL, 
    FAQ_SAVE_REQUEST, 
    FAQ_SAVE_SUCESS,
    FAQ_DELETE_SUCESS,
    FAQ_DELETE_FAIL,
    FAQ_DELETE_REQUEST,
    FAQ_DETAIL_FAIL,
    FAQ_DETAIL_REQUEST,
    FAQ_DETAIL_SUCESS,
    FAQ_LIST_FAIL,
    FAQ_LIST_REQUEST,
    FAQ_LIST_SUCESS
};
